package eu.europa.ec.een;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-05T16:09:47.382+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://een.ec.europa.eu/tools/services", name = "IPODServiceSOAP")
@XmlSeeAlso({com.microsoft.schemas._2003_10.Serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.ObjectFactory.class, eu.europa.ec.een.tools.services.ObjectFactory.class, com.microsoft.schemas._2003_10.Serialization.Arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.ObjectFactory.class})
public interface IPODServiceSOAP {

    @WebMethod(operationName = "GetProfilesSOAP", action = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetProfilesSOAP")
    @Action(input = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetProfilesSOAP", output = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetProfilesSOAPResponse")
    @RequestWrapper(localName = "GetProfilesSOAP", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetProfilesSOAP")
    @ResponseWrapper(localName = "GetProfilesSOAPResponse", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetProfilesSOAPResponse")
    @WebResult(name = "GetProfilesSOAPResult", targetNamespace = "http://een.ec.europa.eu/tools/services")
    public org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.ArrayOfprofileType getProfilesSOAP(
        @WebParam(name = "request", targetNamespace = "http://een.ec.europa.eu/tools/services")
        org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.ProfileQueryRequest request
    );

    @WebMethod(operationName = "SaveProfile", action = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/SaveProfile")
    @Action(input = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/SaveProfile", output = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/SaveProfileResponse")
    @RequestWrapper(localName = "SaveProfile", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.SaveProfile")
    @ResponseWrapper(localName = "SaveProfileResponse", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.SaveProfileResponse")
    @WebResult(name = "SaveProfileResult", targetNamespace = "http://een.ec.europa.eu/tools/services")
    public java.lang.String saveProfile(
        @WebParam(name = "request", targetNamespace = "http://een.ec.europa.eu/tools/services")
        org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.ProfileInputType request,
        @WebParam(name = "credentials", targetNamespace = "http://een.ec.europa.eu/tools/services")
        org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.CredentialsType credentials
    );

    @WebMethod(operationName = "GetEvents", action = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetEvents")
    @Action(input = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetEvents", output = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetEventsResponse")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetEventsResponse")
    @WebResult(name = "GetEventsResult", targetNamespace = "http://een.ec.europa.eu/tools/services")
    public org.datacontract.schemas._2004._07.ArrayOfevent getEvents(
        @WebParam(name = "request", targetNamespace = "http://een.ec.europa.eu/tools/services")
        org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.EventQueryRequestType request
    );

    @WebMethod(operationName = "GetKeywordsSOAP", action = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetKeywordsSOAP")
    @Action(input = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetKeywordsSOAP", output = "http://een.ec.europa.eu/tools/services/IPODServiceSOAP/GetKeywordsSOAPResponse")
    @RequestWrapper(localName = "GetKeywordsSOAP", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetKeywordsSOAP")
    @ResponseWrapper(localName = "GetKeywordsSOAPResponse", targetNamespace = "http://een.ec.europa.eu/tools/services", className = "eu.europa.ec.een.tools.services.GetKeywordsSOAPResponse")
    @WebResult(name = "GetKeywordsSOAPResult", targetNamespace = "http://een.ec.europa.eu/tools/services")
    public org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.KeywordsType getKeywordsSOAP(
        @WebParam(name = "request", targetNamespace = "http://een.ec.europa.eu/tools/services")
        org.datacontract.schemas._2004._07.EEN_Merlin_Backend_Core_BO_PODService.KeywordQueryRequestType request
    );
}
