package eu.europa.ec.een;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-05T16:09:47.566+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "QueryService", 
                  wsdlLocation = "http://een.ec.europa.eu/tools/services/podv6/QueryService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class QueryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryService");
    public final static QName BasicHttpBindingIPODServiceSOAP = new QName("http://tempuri.org/", "BasicHttpBinding_IPODServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://een.ec.europa.eu/tools/services/podv6/QueryService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://een.ec.europa.eu/tools/services/podv6/QueryService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IPODServiceSOAP
     */
    @WebEndpoint(name = "BasicHttpBinding_IPODServiceSOAP")
    public IPODServiceSOAP getBasicHttpBindingIPODServiceSOAP() {
        return super.getPort(BasicHttpBindingIPODServiceSOAP, IPODServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPODServiceSOAP
     */
    @WebEndpoint(name = "BasicHttpBinding_IPODServiceSOAP")
    public IPODServiceSOAP getBasicHttpBindingIPODServiceSOAP(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPODServiceSOAP, IPODServiceSOAP.class, features);
    }

}
